version: '3'

services:

  back-end:   
    container_name: back-end
    build: ./app/back-end
    command: yarn run dev
    ports:
      - 8080:8080
    volumes:
      - /usr/back-end/node_modules
      - ./app/back-end/:/usr/back-end
    environment:
      MYSQL_HOST: mysql_top_commerce
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: top_commerce_db  
    restart: always  
    depends_on:
      - data-base

  front-end:   
    container_name: front-end
    build: ./app/front-end
    command: yarn run dev
    ports:
      - 3000:3000
    volumes:
      - /usr/front-end/node_modules
      - ./app/front-end/:/usr/front-end
    restart: always  
    depends_on:
      - back-end

  data-base:
    image: mysql:latest
    container_name: data-base
    hostname: mysql_top_commerce
    restart: always
    ports:
      - '3306:3306'    
    volumes:
      - ~/.MySQLDBData/mysqlonly/top-commerce-db-data:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: top_commerce_db

volumes:
  top-commerce-db-data:

